before_script:
  - mysql -e 'create database mifosplatform-tenants;'
  - mysql -e 'create database mifostenant-default;'
language: java
jdk:
  - openjdk6
script: ./travis_build.sh
notifications:
  email: true
