before_script:
  - mysql -uroot  -e 'create database mifosplatform_tenants ;'
  - mysql -uroot  -e 'create database mifostenant_default ;'
language: java
jdk:
  - openjdk6
script: ./travis_build.sh
notifications:
  email: true
